pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'cd todo-replace-me/docker-compose && docker-compose build'
            }
        }
        stage('up') {
            steps {
                sh 'cd todo-replace-me/docker-compose && docker-compose up -d'
            }
        }
        stage('down') {
            steps {
                sh 'cd todo-replace-me/docker-compose && docker-compose down --rmi local --volumes'
            }
        }
    }
}
