pipeline {
    agent any
    stages {
        stage('init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('plan') {
            steps {
                sh 'terraform plan -no-color -out tf.plan'
            }
        }
    }
}
